# Generated by Django 3.0.7 on 2020-07-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_reminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
